# Generated by Django 4.2.4 on 2023-08-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('style', models.CharField(max_length=30)),
            ],
        ),
    ]
